service: aws-node-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/function/handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
